project:
  resources: ["images"]
  type: website
  output-dir: docs
  preview:
    port: 0666


website:
  title: "Utah County Political Data"
  favicon: images/favicon.ico
  description: "Utah County Data for Progress"
  site-url: "https://utcounty.github.io" 
  open-graph: true
  twitter-card: true
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - Caucus Night is Tuesday, March 17, 2026"
    type: primary
    position: above-navbar


format:
  html:
    css: styles/styles.css


