project:
  resources: ["images"]
  type: website
  output-dir: docs
  preview:
    port: 0666


website:
  title: "Utah County Political Data"
  favicon: images\favicon.png
  description: "Utah County Data for Progress"
  site-url: "https://ajaverett.com" 
  open-graph: true
  twitter-card: true


format:
  html:
    css: styles/styles.css


